name: newsapp
description: A new Flutter application.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cached_network_image: ^2.3.3
  fluttertoast: ^7.1.6
  flutter_web_browser: ^0.13.0
  webfeed:
    git: https://github.com/Adem68/webfeed.git
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_analytics: ^6.3.0
  google_sign_in: ^4.5.6
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  adaptive_theme: ^1.1.0

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"
  build_runner: ^1.10.11
  mobx_codegen: ^1.1.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon1.jpg"

flutter:
  uses-material-design: true
  assets:
    - assets/
